### ISSUE TITLE
Infinite Logs conflicting with Debug Menu loghack...

### ISSUE THREAD

**Issue by Raszagal** [Wolf11221/SOTF_ModMenu#15]
Not sure why, but the "loghack" debug command only partially works with the 1.4.0 update with Infinite Logs.

I love the idea of Infinite Logs, but I would much prefer if it functioned closer to "loghack" in the way that you can turn it on and whenever you are carrying a log it is infinite, but it also allows you to toss it and have clear hands.

For example, I used "loghack" to place the foundation layout then toss the log I am carrying to be able to cut it into 1/4 and 1/2 logs and then pick those up and have infinite of those to raise the building's actual floor above the grass height. I would then cut a log into planks then pick the planks up to have infinite of those to place the floor. Then go nuts finishing the structure and when finished just turn "loghack" off.

I am unable to do this with Infinite Logs option now. For now, I'll go back to a version that doesn't have Infinite Logs.

I love the mod so far and can't wait to see what else you have planned.

**Comment by Wolf11221** [comment]
If you want to be able to toss the logs and not get duplicated you can use infinite build in the world section instead of infinite logs.

**Comment by Raszagal** [comment]
> If you want to be able to toss the logs and not get duplicated you can use infinite build in the world section instead of infinite logs.

Okay, that does exactly what I like. Thank you for letting me know that would work for me. You can disregard the above then!

Keep up the awesome work!
