### ISSUE TITLE
ModMenu.cfg is missing.

### ISSUE THREAD

**Issue by EoLykos** [Wolf11221/SOTF_ModMenu#16]
Was updating my mods manually and noticed there is no modmenu.cfg in the zip file anymore. Just seeing if this was intended due to a problem or just missed it in the packaging ;) Thank you !!

**Comment by EoLykos** [comment]
Okay, for some reason I don't know how the cfg is showing up in the Bepinex folder now. Not sure how it just showed up but, I checked again and the modmenu.cfg is still not in the zip file lol.

**Comment by Wolf11221** [comment]
The config file (SOTF_ModMenu.cfg) gets created automatically when the game is launched
