### ISSUE TITLE
ESP doesn't disappear after the Enemies/NPCs die.

### ISSUE THREAD

**Issue by i-have-two-moms** [Wolf11221/SOTF_ModMenu#18]
Would love if the ESP for enemies and NPCs would disappear after they die.

**Comment by WoodenSquid** [comment]
> Would love if the ESP for enemies and NPCs would disappear after they die.

it won't disappear if the body is still there. usually will go away when the body despawns

**Comment by i-have-two-moms** [comment]
> > Would love if the ESP for enemies and NPCs would disappear after they die.
> 
> it won't disappear if the body is still there. usually will go away when the body despawns

But why have it like that? It's just confusing to constantly have enemies show up not knowing if they're dead or alive. Maybe have it show a skull or something to indicate that they're dead or an option to make it disappear as soon as they die.

I love the menu and appreciate the work you've put in. This is just a small detail that somewhat bothers me.

**Comment by WoodenSquid** [comment]
> > > Would love if the ESP for enemies and NPCs would disappear after they die.
> > 
> > 
> > it won't disappear if the body is still there. usually will go away when the body despawns
> 
> But why have it like that? It's just confusing to constantly have enemies show up not knowing if they're dead or alive. Maybe have it show a skull or something to indicate that they're dead or an option to make it disappear as soon as they die.
> 
> I love the menu and appreciate the work you've put in. This is just a small detail that somewhat bothers me.

I didn't make it to display the dead bodies, that's just how it works. There is a list of actors and It loops through it displaying them. 
I am not sure there is an indication in the object that determines if it's dead, but I can look later.
