### ISSUE TITLE
Mouse not working

### ISSUE THREAD

**Issue by D4ngrs** [Wolf11221/SOTF_ModMenu#20]
Since the ModMenu uses the mouse, I cant use the Mosue when I want to save the game. If I turn off the menu, the mouse is still around, but clicking any button from the game itself wont work. Only happens since I got this menu installed.

**Comment by WoodenSquid** [comment]
I believe this can be resolved by using the version 1.3.1 of BepInEx ConfigurationManager [here](https://boneworks.thunderstore.io/c/sons-of-the-forest/p/faulty/BepInEx_ConfigurationManager/)

**Comment by Wolf11221** [comment]
Fixed in 1.4.3
