### ISSUE TITLE
FindObjectOfType costly

### ISSUE THREAD

**Issue by faultyd3v** [Wolf11221/SOTF_ModMenu#3]
FindObjectOfType is costly, especially when called every frame in Update()

Source: https://docs.unity3d.com/ScriptReference/Object.FindObjectOfType.html
> Please note that this function is very slow. It is not recommended to use this function every frame.

Consider caching.
```
  if (this.vitals == null)
  {
    this.vitals = UnityEngine.Object.FindObjectOfType<Vitals>();
  }
  if (this.vitals != null)
  {
    // do stuff
  }
```

**Comment by Wolf11221** [comment]
Removed FindObjectOfType in the newest update.
