### ISSUE TITLE
SOTF Mod menu does not work in V1.0

### ISSUE THREAD

**Issue by KnightTheTerrier** [Wolf11221/SOTF_ModMenu#32]
![Screenshot 2024-03-09 144108](https://github.com/Wolf11221/SOTF_ModMenu/assets/129225431/b41a7f2a-4882-4182-8ff6-7f4163183558)

mod menu does not work in V1.0, When running the game you are unable to open it and a error is repeatedly spammed in the BepInEx console.

**Comment by Wolf11221** [comment]
Hello, I have the update for V1.0 almost ready but I need to fix some bugs and I think it should be finished tomorrow.

**Comment by KnightTheTerrier** [comment]
alright, thanks for the support!
