### ISSUE TITLE
No Config File

### ISSUE THREAD

**Issue by TheInfamous404** [Wolf11221/SOTF_ModMenu#4]
Please add a config file so we can change the input key to open the mod menu.

**Comment by Wubzzz1337** [comment]
Yes, please add this! I use TAB for my Inventory 👍

**Comment by Cubly** [comment]
TAB is the worst option for a menu button. It's almost always used by gameplay and most people swap it to inventory. 
If no config file, at least make one of the F keys the hotkey.

**Comment by Wolf11221** [comment]
Added by @Maalik27 in the new version
