### ISSUE TITLE
Ability to hide game HUD

### ISSUE THREAD

**Issue by faultyd3v** [Wolf11221/SOTF_ModMenu#6]
Please add the ability to hide game HUD (useful for screenshots for example).

Couple of ways this can be done.
First way would be to cache the GameObject "PlayerStandin" since you can't "Find" an inactive object
```
GameObject playerObj = GameObject.Find("PlayerStandin");

playerObj.SetActive(boolean);
```

Or else I guess you're having to find it like this?
```
foreach (GameObject gObject in UnityEngine.SceneManagement.SceneManager.GetSceneByName("SonsMain").GetRootGameObjects())
{
    if (gObject.name == "PlayerStandin")
    {
        gObject.SetActive(boolean);
        break;
    }
}
```

**Comment by Wolf11221** [comment]
Added in the new version.
