### ISSUE TITLE
Menu not showing up

### ISSUE THREAD

**Issue by SaipanDamashii** [Wolf11221/SOTF_ModMenu#7]
Since the update to the new version, the menu no longer shows up when I press backquote, tilde, or even tab like the old hotkey was set to.  I even set it to a new key on Bepinex config manager thingy and it still wouldn't work.  Anyone else having this issue?

**Comment by EugeneSoftwareDeveloper** [comment]
Try F2 Hotkeys

Toggle = F2

**Comment by EugeneSoftwareDeveloper** [comment]
> Since the update to the new version, the menu no longer shows up when I press backquote, tilde, or even tab like the old hotkey was set to. I even set it to a new key on Bepinex config manager thingy and it still wouldn't work. Anyone else having this issue?

Try F2 Hotkeys. 

Toggle = F2


File for edit "...\Sons Of The Forest\BepInEx\config\SOTF ModMenu.cfg"

**Comment by Wolf11221** [comment]
Please send me the log file located at BepInEx/LogOutput.log so that I can check the problem

**Comment by Bexya** [comment]
I have the same problem and here's the log file:
[LogOutput.log](https://github.com/Wolf11221/SOTF_ModMenu/files/10902646/LogOutput.log)

I have these mods installed:
- https://thunderstore.io/c/sons-of-the-forest/p/willis81808/Mache/ 
- https://thunderstore.io/c/sons-of-the-forest/p/Fang86/Warps/
- https://thunderstore.io/c/sons-of-the-forest/p/jakzo/KelvinCloner/
- https://thunderstore.io/c/sons-of-the-forest/p/faulty/Crash_Site_Selector/
- https://thunderstore.io/c/sons-of-the-forest/p/faulty/BepInEx_ConfigurationManager/
- https://thunderstore.io/c/sons-of-the-forest/p/ElGringo/InfiniteZipline/
- https://thunderstore.io/c/sons-of-the-forest/p/Fang86/Flight/
- https://thunderstore.io/c/sons-of-the-forest/p/BepInEx/BepInExPack_IL2CPP/ 
- https://thunderstore.io/c/sons-of-the-forest/p/Mythic/SOTF_Autosave/
- https://thunderstore.io/c/sons-of-the-forest/p/CallMeSlinky/DebugConsole/

Also no keybindings seem to be overlapping.

**Comment by Wolf11221** [comment]
Download the latest version from [github](https://github.com/Wolf11221/SOTF_ModMenu/releases/tag/v1.1.3) to see if the problem has been fixed, if not send me the LogOutput.log file again

**Comment by EGUltraTM** [comment]
Look in your config folder. The cfg has changed with an _ if you delete the old one it works fine again. Had the same issue
